service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.

eksCluster: false

image:
  repository: coco/content-fluentd
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 600m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 200Mi
annotations:
  iam.amazonaws.com/role: "K8sSplunkFWS3"
