service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.

image:
  repository: coco/content-fluentd
  pullPolicy: Always

resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 200Mi
