service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.


image:
  repository: coco/content-fluentd
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 1000m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 200Mi

annotations:
  iam.amazonaws.com/role: "eksctl-content-fluentd-kinesis-role-eks-delivery-dev-eu"
