apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ .Values.service.name }}
  labels:
    chart: "{{ .Chart.Name | trunc 63 }}"
    chartVersion: "{{ .Chart.Version | trunc 63 }}"
    app: {{ .Values.service.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  updateStrategy:
    type: "RollingUpdate"
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      tolerations:
      - operator: "Exists"
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        env:
        - name: ENVIRONMENT_NAME
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: environment
        - name: KINESIS_STREAM
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: content.fluentd.kinesis.stream
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: content-fluentd
              key: aws.access.key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: content-fluentd
              key: aws.secret.access.key
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: content-fluentd
              key: aws.region
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: content-fluentd
              key: s3.access.key
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: content-fluentd
              key: s3.secret.access.key
        ports:
        - name: http-input
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: "/fluentd.pod.healthcheck?json=%7B%22log%22%3A+%22health+check%22%7D"
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
